name: CMake

on:
 push:
  branches: [master]
  tags: -"v0.1.*.*"
 pull_request:
  branches: [master]
env:
  BUILD_TYPE: Release
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Packing
      run: |
        cmake -H. -B_build
        cmake --build _build
        cd _build
        cpack -G "TGZ"
        cpack -G "DEB"
        cpack -G "RPM"
        cd ..
        cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
        cmake --build _build --target package
             
    - name: Moving
      run: |
        mkdir ../artifacts
        mv *.tar.gz ../artifacts/
        mv *.deb ../artifacts/
        mv *.rpm ../artifacts/

    - name: Public
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifacts/
